"""
fix_bear_fvg_detection.py — patch detect_ict_patterns.py to add BEAR_FVG support.

Context:
  ADR-004 (Canon Deviations, to be filed at session close) — finding 1 of N:
  detect_ict_patterns.py only detects BULL_FVG. BEAR_FVG never generated by
  runtime detector. Phase 1 audit confirmed 0 W BEAR_FVG zones over 8 weeks.

Decision (this session):
  - Detection: symmetric. Add BEAR_FVG detection mirroring BULL_FVG.
  - Routing: SKIP. assign_tier() returns "SKIP" for BEAR_FVG always.
  - Rationale: Compendium evidence — BEAR_FVG raw N=225, 11.5% WR, -30.7% exp.
    Negative buyer edge regardless of context. Detect for MTF context and
    future strategies; never auto-route as BUY_PE.

What this script changes (in C:\\GammaEnginePython\\detect_ict_patterns.py):

  1. OPT_TYPE dict          — add "BEAR_FVG": "PE"
  2. DIRECTION dict         — add "BEAR_FVG": -1
  3. detect_fvg() function  — add symmetric bearish branch
  4. assign_tier()          — hardcode "SKIP" for BEAR_FVG before other rules
  5. ICTDetector.detect()   — zone level branch for BEAR_FVG
                              (zone_high = bars[idx-1].low, zone_low = bars[idx+1].high)

Idempotency:
  Script checks for marker "# BEAR_FVG_PATCH_APPLIED" near top of target file.
  If present, prints "already patched" and exits 0. Otherwise applies edits
  and writes the marker.

Pre-state verification:
  Script asserts the exact source strings it expects to find before replacing.
  If any expected string is missing (file modified since this fix was authored),
  script aborts with diagnostic and changes nothing.

Backup:
  Writes detect_ict_patterns.py.bak_pre_bear_fvg before any modification.
  If you need to roll back: copy .bak file over the live one.

AST validation:
  After all edits, re-parses the modified file with ast.parse(). If parse
  fails, restores from backup and aborts.

Run on Local Windows from C:\\GammaEnginePython:
    python fix_bear_fvg_detection.py
"""

from __future__ import annotations

import ast
import shutil
import sys
from pathlib import Path

TARGET = Path("detect_ict_patterns.py")
BACKUP = Path("detect_ict_patterns.py.bak_pre_bear_fvg")
MARKER = "# BEAR_FVG_PATCH_APPLIED"


# ── Edit specifications ──────────────────────────────────────────────
# Each edit: (description, expected_old, new). Strings are exact and
# include surrounding context to ensure unique match.

EDITS = [
    (
        "1. OPT_TYPE dict — add BEAR_FVG: PE",
        '''OPT_TYPE = {
    "BULL_OB":    "CE",
    "BEAR_OB":    "PE",
    "BULL_FVG":   "CE",
    "JUDAS_BULL": "CE",
}''',
        '''OPT_TYPE = {
    "BULL_OB":    "CE",
    "BEAR_OB":    "PE",
    "BULL_FVG":   "CE",
    "BEAR_FVG":   "PE",
    "JUDAS_BULL": "CE",
}''',
    ),
    (
        "2. DIRECTION dict — add BEAR_FVG: -1",
        '''DIRECTION = {
    "BULL_OB":    +1,
    "BEAR_OB":    -1,
    "BULL_FVG":   +1,
    "JUDAS_BULL": +1,
}''',
        '''DIRECTION = {
    "BULL_OB":    +1,
    "BEAR_OB":    -1,
    "BULL_FVG":   +1,
    "BEAR_FVG":   -1,
    "JUDAS_BULL": +1,
}''',
    ),
    (
        "3. detect_fvg() — add symmetric BEAR_FVG branch",
        '''def detect_fvg(bars: list[Bar]) -> list[tuple[int, str]]:
    """
    Detect Bullish Fair Value Gaps.
    Gap between bars[i-1].high and bars[i+1].low > FVG_MIN_PCT.
    Pattern bar is bars[i] (the middle bar).
    """
    results = []
    min_g   = FVG_MIN_PCT / 100.0

    for i in range(1, len(bars) - 1):
        prev, curr, nxt = bars[i - 1], bars[i], bars[i + 1]
        ref = curr.close
        if prev.high < nxt.low and (nxt.low - prev.high) / ref >= min_g:
            results.append((i, "BULL_FVG"))

    return results''',
        '''def detect_fvg(bars: list[Bar]) -> list[tuple[int, str]]:
    """
    Detect Fair Value Gaps (3-bar imbalance), both directions.

    BULL_FVG: prev.high < nxt.low (gap upward, candle 1 high below candle 3 low).
    BEAR_FVG: prev.low  > nxt.high (gap downward, candle 1 low above candle 3 high).

    Pattern bar is bars[i] (the middle / displacement bar).
    Detection is symmetric per ICT canon. ROUTING for BEAR_FVG is SKIP
    (see assign_tier — Compendium: BEAR_FVG raw N=225, 11.5% WR, -30.7% exp).
    """
    results = []
    min_g   = FVG_MIN_PCT / 100.0

    for i in range(1, len(bars) - 1):
        prev, curr, nxt = bars[i - 1], bars[i], bars[i + 1]
        ref = curr.close
        if not ref:
            continue
        if prev.high < nxt.low and (nxt.low - prev.high) / ref >= min_g:
            results.append((i, "BULL_FVG"))
        elif prev.low > nxt.high and (prev.low - nxt.high) / ref >= min_g:
            results.append((i, "BEAR_FVG"))

    return results''',
    ),
    (
        "4. assign_tier() — hardcode SKIP for BEAR_FVG",
        '''    # BULL_FVG and JUDAS_BULL
    # ENH-64 sub-rule 3: BULL_FVG LOW_IV skip.
    # 0% WR N=23, -14.3% exp (Exp 5).
    if pattern_type == "BULL_FVG" and atm_iv is not None and atm_iv < LOW_IV_THRESHOLD:
        return "SKIP"
    return "TIER2"''',
        '''    # BEAR_FVG: detect for MTF context and future strategies, but NEVER route
    # as BUY_PE. Compendium evidence: raw N=225, 11.5% WR, -30.7% expectancy.
    # Negative buyer edge regardless of IV / context / DTE. Hardcoded SKIP
    # is the routing-policy enforcement point per ADR-004.
    if pattern_type == "BEAR_FVG":
        return "SKIP"

    # BULL_FVG and JUDAS_BULL
    # ENH-64 sub-rule 3: BULL_FVG LOW_IV skip.
    # 0% WR N=23, -14.3% exp (Exp 5).
    if pattern_type == "BULL_FVG" and atm_iv is not None and atm_iv < LOW_IV_THRESHOLD:
        return "SKIP"
    return "TIER2"''',
    ),
    (
        "5. ICTDetector.detect() — zone level branch for BEAR_FVG",
        '''            # Zone levels
            if pattern_type in ("BULL_OB", "BEAR_OB"):
                zone_high = max(bar.open, bar.close)
                zone_low  = min(bar.open, bar.close)
            elif pattern_type == "BULL_FVG":
                # Gap between prior bar high and next bar low
                if idx > 0 and idx < len(bars) - 1:
                    zone_low  = bars[idx - 1].high
                    zone_high = bars[idx + 1].low
                else:
                    zone_high = bar.high
                    zone_low  = bar.low
            else:
                # JUDAS_BULL — use bar range
                zone_high = bar.high
                zone_low  = bar.low''',
        '''            # Zone levels
            if pattern_type in ("BULL_OB", "BEAR_OB"):
                zone_high = max(bar.open, bar.close)
                zone_low  = min(bar.open, bar.close)
            elif pattern_type == "BULL_FVG":
                # Gap between prior bar high and next bar low
                if idx > 0 and idx < len(bars) - 1:
                    zone_low  = bars[idx - 1].high
                    zone_high = bars[idx + 1].low
                else:
                    zone_high = bar.high
                    zone_low  = bar.low
            elif pattern_type == "BEAR_FVG":
                # Gap between next bar high and prior bar low (mirror of BULL_FVG)
                if idx > 0 and idx < len(bars) - 1:
                    zone_high = bars[idx - 1].low
                    zone_low  = bars[idx + 1].high
                else:
                    zone_high = bar.high
                    zone_low  = bar.low
            else:
                # JUDAS_BULL — use bar range
                zone_high = bar.high
                zone_low  = bar.low''',
    ),
]


def main() -> int:
    print("=" * 70)
    print("fix_bear_fvg_detection.py — patching detect_ict_patterns.py")
    print("=" * 70)

    if not TARGET.exists():
        print(f"[FATAL] {TARGET} not found in current directory.")
        print(f"        cd to C:\\GammaEnginePython and re-run.")
        return 2

    src = TARGET.read_text(encoding="utf-8")

    # Idempotency check
    if MARKER in src:
        print(f"[idempotent] marker {MARKER!r} found — already patched. No changes.")
        return 0

    # Pre-state verification: every expected old string must be present exactly once
    print("\nPre-state verification:")
    for desc, old, _ in EDITS:
        n = src.count(old)
        status = "OK" if n == 1 else f"FAIL (found {n} matches, expected 1)"
        print(f"  [{status}] {desc}")
        if n != 1:
            print(f"\n[FATAL] Edit '{desc}' cannot be applied safely.")
            print(f"        Expected exactly 1 match for the old string, found {n}.")
            print(f"        File may have been modified since this patch was authored.")
            print(f"        No changes written. Backup not created.")
            return 3

    # Backup
    print(f"\n[backup] writing {BACKUP}")
    shutil.copy2(TARGET, BACKUP)

    # Apply edits
    print("\nApplying edits:")
    new_src = src
    for desc, old, new in EDITS:
        new_src = new_src.replace(old, new, 1)
        print(f"  [applied] {desc}")

    # Inject idempotency marker near top (after module docstring, before imports)
    marker_block = f"\n{MARKER}  # added by fix_bear_fvg_detection.py — see ADR-004\n"
    # Insert after the closing triple-quote of the module docstring
    # Look for first `from __future__` or first `import` and insert before it
    insert_anchors = ['from __future__ import annotations', '\nimport os']
    inserted = False
    for anchor in insert_anchors:
        if anchor in new_src:
            new_src = new_src.replace(anchor, marker_block + anchor, 1)
            inserted = True
            break
    if not inserted:
        # Fallback: append at end of file
        new_src = new_src + "\n" + marker_block

    # Write
    TARGET.write_text(new_src, encoding="utf-8")

    # AST validation
    print("\nAST validation:")
    try:
        ast.parse(new_src)
        print("  [OK] AST parse clean")
    except SyntaxError as e:
        print(f"  [FAIL] SyntaxError: {e}")
        print(f"  [rollback] restoring from {BACKUP}")
        shutil.copy2(BACKUP, TARGET)
        print(f"  [rollback] complete. {TARGET} restored to pre-patch state.")
        return 4

    print("\n" + "=" * 70)
    print("PATCH APPLIED SUCCESSFULLY")
    print("=" * 70)
    print(f"  Modified : {TARGET}")
    print(f"  Backup   : {BACKUP}")
    print(f"  Marker   : {MARKER}")
    print()
    print("Verification suggested:")
    print("  python -c \"from detect_ict_patterns import OPT_TYPE, DIRECTION; "
          "assert OPT_TYPE['BEAR_FVG']=='PE' and DIRECTION['BEAR_FVG']==-1; "
          "print('imports OK')\"")
    print()
    print("  python -c \"from detect_ict_patterns import assign_tier; "
          "assert assign_tier('BEAR_FVG', {'impulse_strong':False,'mom_aligned':False,"
          "'has_prior_sweep':False}, 'MORNING', 15.0)=='SKIP'; print('routing OK')\"")
    print()
    print("Next: run live cycle / shadow to confirm BEAR_FVG zones appear in ict_zones")
    print("with ict_tier='SKIP' and ict_size_mult=0.0 (signal generation safely blocked).")
    print()
    print("Note: this patches the 5m runtime detector only. The HTF zone producer")
    print("(build_ict_htf_zones.py) likely has the same omission — separate fix script,")
    print("next session.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
